name: Run mark85
run-name: On Push - Mark85-cypress-api
on: [push]

jobs:
    tests-api:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Cypress run
              uses: cypress-io/github-action@v6